### PR TITLE
Add github contribute button

### LINKED ISSUE #44: Add "fork me" / "contribute" link to homepage
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
We should provide a link to encourage users to contribute. The link should go to the repo on github.

**Describe alternatives you've considered**
We could just lik the repo in the footer.

**Additional context**
This was included in our original event storm.

### PR DESCRIPTION
**Pull request by TheGLander**
Fixes #44

### CODE REVIEW

**Comment by TheGLander** [comment]
I wonder why that deploy is broken, doing 
```
yarn install
yarn run build
```
works on my machine

**Comment by vabatta** [comment]
No worry about the failed deployment, is because we added stuff to the repo's pipeline but haven't configured it yet.

**Review by vabatta — APPROVED** [review]
LGTM 🎉

**Comment by TheGLander** [comment]
Ah, okay, thanks for letting me know

**Review by jamescallumyoung — APPROVED** [review]
LGTM

**Pull request merged**
