### PR TITLE
redirect ezlint to homepage

### PR DESCRIPTION
**Pull request by gixid192**
fix issue #43 

Please let me know if this is what you need.

### CODE REVIEW

**Comment by jamescallumyoung** [comment]
Hi @gixid192, thanks for taking a look at this 😃

I don't believe this solution is what we're looking for. I'll try to explain below:

The site is _actually_ hosted at `ezlint.github.io/ezlint/`. A redirect fixes the issue of the page not rendering but it will rewrite the browser history to show the user they're at `ezlint.github.io`. That address is not valid.

I think a better solution would be to include a basepath in the router so it matches correctly when hosted on a non-root path.

Feel free to ping me if you have any questions and thanks again for getting involved!

**Comment by gixid192** [comment]
I'm not sure that I fully understand your requirement.

How about mapping both `/` and `/ezlint` to `Home` component?

**Comment by vabatta** [comment]
The root of the GitHub pages is located at `/ezlint/` rather than `/`, this means that in the `react-router` the path `/` should render the home while the `/ezlint/` should just not be there (it would corresponds to the url `/ezlint/ezlint/` which is not "pretty").

**Comment by gixid192** [comment]
ok I see, it's about the deployment, not the router, I don't think this PR is needed anymore, will close it from here.

**Pull request closed without merging**
